//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSubject
    {
        public StudentSubject()
        {
            this.GradesRecord = new HashSet<GradesRecord>();
            this.ZaverkiRecord = new HashSet<ZaverkiRecord>();
        }
    
        public int ID { get; set; }
        public int FN { get; set; }
        public int SID { get; set; }
    
        public virtual ICollection<GradesRecord> GradesRecord { get; set; }
        public virtual Students Students { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual ICollection<ZaverkiRecord> ZaverkiRecord { get; set; }
    }
}
