//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects
    {
        public Subjects()
        {
            this.StudentSubject = new HashSet<StudentSubject>();
            this.TeacherSubject = new HashSet<TeacherSubject>();
        }
    
        public int SID { get; set; }
        public string SubjectName { get; set; }
        public string Type { get; set; }
        public System.DateTime ExamDate { get; set; }
    
        public virtual ICollection<StudentSubject> StudentSubject { get; set; }
        public virtual ICollection<TeacherSubject> TeacherSubject { get; set; }
    }
}
